spring.application.name=student-api
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# JWT settings
# secret base64 me hai (production me ise environment variable se aana chahiye, code me nahi)
jwt.secret=ovDW6FTaJEuqP6uauQMyJxK2mbE/v1djHG7i6fyIEU1U3ySJnHeTcpaLjy26F9SE
# token kitni der valid rahega (milliseconds me) — abhi 24 ghante
jwt.expiration=86400000
